sudo: required

services:
  - docker

before_install:
  - docker --version

language: java

cache:
  directories:
  - $HOME/.m2

script: 
  - docker --version
  - docker-compose --version
  - cd docker-images/oa-java-server/
  - ./build-docker-image.sh
  - cd ../oa-server-specs/
  - ./build-docker-image.sh
  - cd ../../docker-topologies/runtime
  - docker-compose up -d
  - sleep 30
  - cd ../../docker-images/oa-server-specs/
  - ./run-docker-image.sh
  - cd ../../docker-topologies/runtime
  - docker-compose down

