version: '3'
services:
  mysql-auth:
    build: ../microservices/auth-service/images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
  mysql-shop:
    build: ../microservices/shop-service/images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
  server-auth:
    build: ../microservices/auth-service/images/alpine-java
    entrypoint: ["/opt/wait_for_it.sh","mysql-auth:3306","--","java","-jar","/opt/auth-api.jar"]
    environment:
      - spring_datasource_url=jdbc:mysql://mysql-auth:3306/userdb
      - token_secret=jwtsecret
    depends_on:
      - mysql-auth
    ports:
      - "8080:8080"
  server-shop:
    build: ../microservices/shop-service/images/alpine-java
    entrypoint: ["/opt/wait_for_it.sh","mysql-shop:3306","--","java","-jar","/opt/shop-api.jar"]
    environment:
      - spring_datasource_url=jdbc:mysql://mysql-shop:3306/shopdb
      - token_secret=jwtsecret
    depends_on:
      - mysql-shop
    ports:
      - "8081:8081"
  phpmyadmin:
    build: ./images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
     - PMA_HOSTS=mysql-auth, mysql-shop
    ports:
     - "6060:80"