version: '3'
services:
  mysql-auth:
    build: ../microservices/auth-service/images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "3306:3306"
  mysql-shop:
    build: ../microservices/shop-service/images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3307:3306"
  phpmyadmin:
    build: ./images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
     - PMA_HOSTS=mysql-auth, mysql-shop
    ports:
     - "6060:80"