swagger: '2.0'
info:
  version: '0.1.0'
  title: Users API
  description: An API to demonstrate Swagger and Spring Boot
host: localhost:8080
basePath: /api
schemes:
  - http

paths:
  /users:
    post:
      description: create a user
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all users
      operationId: getUsers
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /users/{userId}:
    delete:
      description: delete a user
      operationId: deleteUser
      consumes:
        - application/json
      parameters:
        - in: path
          name: userId
          required: true
          type: string
      responses:
        '201':
          description: created
          schema:
            type: object
definitions:
  User:
    type: object
    properties:
      email:
        type: string
      isAdmin:
        type: boolean
      FirstName:
        type: string
      LastName:
        type: string
      Password:
        type: string
